config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :photos
  devise_for :users
  resources :signups
  resources :buskings
  resources :performances
  resources :tips
  resources :posts
  resources :tests
  
  resources :comments, only: [:create, :destroy]
  
  # my page
  get '/my_page', to: 'main#mypage', as: 'my_page'

  root 'main#index'
  get 'users/sign_in'
  get'/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destory'
  
  # 홈화면
  get 'main/index'
  get 'mail/main'
  
  # mail
  get 'mail/index'
  post '/mail/write' => 'mail#write'
  
  # line up
  resources :performances, except: [:show] do
     post "/performance_like", to: "performance_likes#performance_like_toggle"
  end
  post '/:x_id/comment_per_create' => 'performances#comment_create'
  get '/:x_id/comment_per_destroy/:c_id' => 'performances#comment_destroy'
  
  
  get '/performances/performance_like/:performance_id' => 'performances#performance_like'

  
  # community
  resources :posts, except: [:show] do
     post "/like", to: "likes#like_toggle"
  end
  post '/:x_id/comment_create' => 'posts#comment_create'
  get '/:x_id/comment_destroy/:c_id' => 'posts#comment_destroy'
  
  get '/posts/like/:post_id' => 'posts#like'
 
  
  
  post 'performances/result'      => 'performances#result'   # 검색 결과 페이지
  get 'performances/result2/:keyword' => 'performances#result2' #다음카카오 API 결과 페이지
  
  
  post 'tips/result'      => 'tips#result'   # 검색 결과 페이지
  get 'tips/result2/:keyword' => 'tips#result2' #다음카카오 API 결과 페이지
  
  post 'buskings/result'      => 'buskings#result'   # 검색 결과 페이지
  get 'buskings/result2/:keyword' => 'buskings#result2' #다음카카오 API 결과 페이지
  
  post 'posts/result'      => 'posts#result'   # 검색 결과 페이지
  get 'posts/result2/:keyword' => 'posts#result2' #다음카카오 API 결과 페이지
  
  # 날짜로 공연 찾기
  get '/main/search'
  
  # tip
  post '/:x_id/comment_tip_create' => 'tips#comment_create'
  get '/:x_id/comment_tip_destroy/:c_id' => 'tips#comment_destroy'
  
  # busking
  post '/:x_id/comment_busking_create' => 'buskings#comment_create'
  get '/:x_id/comment_busking_destroy/:c_id' => 'buskings#comment_destroy'
  
  # like
  post '/post/:post_id/like_per'      => 'likes#like_per_toggle', as: 'like_per'
  post '/post/:post_id/like'          => 'likes#like_toggle', as: 'like_post'
  post '/post/:post_id/like_tip'      => 'likes#like_tip_toggle', as: 'like_tip'
  post '/post/:post_id/like_busking'  => 'likes#like_busking_toggle', as: 'like_busking'
  post '/post/:post_id/like_photo'    => 'likes#like_photo_toggle', as: 'like_photo'
  post '/post/:post_id/like_video'    => 'likes#like_video_toggle', as: 'like_video'
  
  resources :performances, except: [:show] do
     post "/like", to: "likes#like_toggle"
     end
  
   # video
  post '/:x_id/comment_video_create' => 'videos#comment_create'
  get '/:x_id/comment_video_destroy/:c_id' => 'videos#comment_destroy'
   
   # photo
  post '/:x_id/comment_photo_create' => 'photos#comment_create'
  get '/:x_id/comment_photo_destroy/:c_id' => 'photos#comment_destroy'
  
  # 댓글 수정, 삭제
  get '/:x_id/comment_per_edit/:c_id' => 'performances#comment_per_edit', as: 'comment_per_edit'
  post '/:x_id/comment_per_update/:c_id' => 'performances#comment_per_update', as: 'comment_per_update'
  
  get '/:x_id/comment_comu_edit/:c_id' => 'posts#comment_comu_edit', as: 'comment_comu_edit'
  post '/:x_id/comment_comu_update/:c_id' => 'posts#comment_comu_update', as: 'comment_comu_update'
  
  get '/:x_id/comment_tip_edit/:c_id' => 'tips#comment_tip_edit', as: 'comment_tip_edit'
  post '/:x_id/comment_tip_update/:c_id' => 'tips#comment_tip_update', as: 'comment_tip_update'
  
  get '/:x_id/comment_busking_edit/:c_id' => 'buskings#comment_busking_edit', as: 'comment_busking_edit'
  post '/:x_id/comment_busking_update/:c_id' => 'buskings#comment_busking_update', as: 'comment_busking_update'
  
  get '/:x_id/comment_photo_edit/:c_id' => 'photos#comment_photo_edit', as: 'comment_photo_edit'
  post '/:x_id/comment_photo_update/:c_id' => 'photos#comment_photo_update', as: 'comment_photo_update'
  
  get '/:x_id/comment_video_edit/:c_id' => 'videos#comment_video_edit', as: 'comment_video_edit'
  post '/:x_id/comment_video_update/:c_id' => 'videos#comment_video_update', as: 'comment_video_update'
  
  #ed upon order of creation: first created -> highest priority.
  # See how all your ro
  
  
  # The priority is basutes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def mypage
    
  end
  
  def index
    @lastperformances = Performance.limit(3)
    @tips = Tip.limit(5)
    @posts = Post.limit(5)
    @buskings = Busking.limit(5)
    @photos = Photo.limit(3)
    @videos = Video.limit(3)
    @busks = Busking.all
    @performances = Performance.all
  end
  
  def search
    @sdate = params[:searchdate]
    @buskings = Busking.all
    @performances = Performance.all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_busking.html.erb
<% unless current_user.liked_buskings.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Category</th>
        <th>Day</th>
        <th>Place</th>
        <th>Name</th>
        <th>Image</th>
        <th>Content</th>
        <th></th>
        <th>댓글 작성</th>
        <th>댓글 보기</th>
        <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
      </tr>
    </thead>
  
    <tbody>
      <% current_user.liked_buskings.each do |busking| %>
        <tr>
          <td>Busking</td>
          <td><%= busking.day %></td>
          <td><%= busking.place %></td>
          <td><%= busking.name %></td>
          <td>
            <img src="<%= busking.image %>" height="250" width="180"/><br>
            <a href="<%= busking.image %>" target="_blank">크게보기</a> 
          </td>
          <td><%= busking.content %></td>
          <td><%= link_to 'Show', busking %><br>
            <% if busking.user == current_user %>
              <%= link_to 'Edit', edit_busking_path(busking) %><br>
              <%= link_to 'Destroy', busking, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
          
          <!--댓글작성-->
          <td>
            <form action = "/<%= busking.id%>/comment_busking_create" method= "post">
              댓글 : <textarea name="content"></textarea>
              <button type="submit" class="btn btn-default btn-xs">제출</button>
            </form>
          
          </td>
          
          <!--댓글보기-->
          <td>
            <%busking.comment_buskings.each do |c| %>
              <%= fa_icon('comment-alt') %> <%= c.content%>
              <% if c.user == current_user %>
                <%= link_to comment_busking_edit_path(x_id: busking.id, c_id: c.id) do %>
                  수정
                <% end %>
                <a href="<%= busking.id %>/comment_busking_destroy/<%= c.id %>"> 삭제 </a>
              <% end %>
              <br>
            <%end%>
          </td>
          <td>
            <% if busking.liked_busking_users.include?(current_user) %>
              <!--좋아요 누름-->
              <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                          like_busking_path(post_id: busking.id), method: :post %>
            <% else %>
              <!--좋아요 안 누름-->
              <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                          like_busking_path(post_id: busking.id), method: :post %>
            <% end %>
            <%= busking.likebuskings.count %> 명이 좋아합니다. <br><br>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/main/_performance.html.erb
<% unless current_user.liked_pers.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Category</th>
        <th>Date</th>
        <th>Title</th>
        <th>Poster</th>
        <th>Seat</th>
        <th>Content</th>
        <th></th>
        <th>댓글 작성</th>
        <th>댓글 보기</th>
        <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
      </tr>
    </thead>
  
    <tbody>
      <% current_user.liked_pers.each do |performance| %>
        <tr>
          <td>Line Up</td>
          <td><%= performance.day %></td>
          <td><%= performance.title %></td>
          <td>
            <img src="<%= performance.image %>" height="250" width="180"/><br>
            <a href="<%= performance.image %>" target="_blank">크게보기</a>
          </td>
          <td>
            <img src="<%= performance.second %>" height="250" width="180"/><br>
            <a href="<%= performance.second %>" target="_blank">크게보기</a>  
          </td>
          <td><%= performance.content %></td>
          <td>
            <%= link_to "Show", performance %><br>
            
            <% if performance.user == current_user %>
              <%= link_to 'Edit', edit_performance_path(performance) %><br>
              <%= link_to 'Destroy', performance, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </td>
          <!--댓글작성-->
          <td width="8%">
            <form action = "/<%= performance.id%>/comment_per_create" method= "post">
              댓글 : <textarea name="content"></textarea>
              <button type="submit" class="btn btn-default btn-xs">제출</button>
            </form>
          </td>
          
          <!--댓글보기-->
          <td width="15%">
            <% performance.comment_pers.each do |c| %>
              <%= fa_icon('comment-alt') %> <%= c.content%> 
              <% if c.user == current_user %>
                <%= link_to comment_per_edit_path(x_id: performance.id, c_id: c.id) do %>
                  수정
                <% end %>
                <a href="<%= performance.id %>/comment_per_destroy/<%= c.id %>"> 삭제 </a>
                
              <% end %>
              <br>
            <%end%>
            
          </td>
          <td>
              <% if performance.liked_per_users.include?(current_user) %>
                <!--좋아요 누름-->
                <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                            like_per_path(post_id: performance.id), method: :post %>
              <% else %>
                <!--좋아요 안 누름-->
                <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                            like_per_path(post_id: performance.id), method: :post %>
              <% end %>
              <%= performance.likepers.count %> 명이 좋아합니다. <br><br>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/main/_photo.html.erb
<% unless current_user.liked_photos.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Category</th>
        <th>Title</th>
        <th>Image</th>
        <th>Content</th>
        <th></th>
        <th>댓글 작성</th>
        <th>댓글 보기</th>
        <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
      </tr>
    </thead>
  
    <tbody>
      <% current_user.liked_photos.each do |photo| %>
        <tr>
          <td>Photo</td>
          <td><%= photo.title %></td>
          <td><img src="<%= photo.image %>" height="250" width="180"/></td>
          <td><%= photo.content %></td>
          <td><%= link_to 'Show', photo %><br>
            <% if photo.user == current_user %>
              <%= link_to 'Edit', edit_photo_path(photo) %><br>
              <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
          <!--댓글작성-->
          <td>
            <form action = "/<%= photo.id%>/comment_photo_create" method= "post">
              댓글 : <textarea name="content"></textarea>
              <button type="submit" class="btn btn-default btn-xs">제출</button>
            </form>
          
          </td>
          
          <!--댓글보기-->
          <td>
            <% photo.comment_photos.each do |c| %>
              <%= fa_icon('comment-alt') %> <%= c.content%>
              <% if c.user == current_user %>
                <%= link_to comment_photo_edit_path(x_id: photo.id, c_id: c.id) do %>
                  수정
                <% end %>
                <a href="<%= photo.id %>/comment_photo_destroy/<%= c.id %>"> 삭제 </a>
              <% end %>
              <br>
            <%end%>
          </td>
          <td>
              <% if photo.liked_photo_users.include?(current_user) %>
                <!--좋아요 누름-->
                <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                            like_photo_path(post_id: photo.id), method: :post %>
              <% else %>
                <!--좋아요 안 누름-->
                <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                            like_photo_path(post_id: photo.id), method: :post %>
              <% end %>
              <%= photo.likephotos.count %> 명이 좋아합니다. <br><br>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/main/_post.html.erb
<% unless current_user.liked_posts.empty? %>
    <table class="table">
      <thead>
        <tr >
          <th>Category</th>
          <th >title</th>
          <th >content</th>
          <th></th>
          <th>댓글 작성</th>
          <th>댓글 보기</th>
          <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
        </tr>
      </thead>
    
      <tbody>
        <% current_user.liked_posts.each do |post| %>
          <tr>
            <td>Community</td>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td><%= link_to 'Show', post %><br>
              <% if post.user == current_user %>
                <%= link_to 'Edit', edit_post_path(post) %><br>
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
            <!--댓글작성-->
            <td>
              <form action = "/<%=post.id%>/comment_create" method= "post">
                댓글 : <textarea name="content"></textarea>
                <button type="submit" class="btn btn-default btn-xs">제출</button>
              </form>
            </td>
            
            <!--댓글보기-->
            <td>
              <% post.comment_comus.each do |c| %>
                <%= fa_icon('comment-alt') %> <%= c.content%>
                <% if c.user == current_user %>
                  <%= link_to comment_comu_edit_path(x_id: post.id, c_id: c.id) do %>
                    수정
                  <% end %>
                  <a href="<%= post.id %>/comment_destroy/<%= c.id %>"> 삭제 </a>
                <%end%><br>
              <%end%>
            </td>
            <td> 
              <% if post.liked_users.include?(current_user) %>
                <!--좋아요 누름-->
                <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                            like_post_path(post_id: post.id), method: :post %>
              <% else %>
                <!--좋아요 안 누름-->
                <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                            like_post_path(post_id: post.id), method: :post %>
              <% end %>
              <%= post.likes.count %> 명이 좋아합니다. <br><br>
            </td>
          </tr>
          
          
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/main/_tip.html.erb
<% unless current_user.liked_tips.empty? %>
<table class="table">
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Image</th>
      <th>Content</th>
      <th></th>
      <th>댓글 작성</th>
      <th>댓글 보기</th>
      <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.liked_tips.each do |tip| %>
      <tr>
        <td>Tip</td>
        <td><%= tip.title %></td>
        <td>
          <img src="<%= tip.image %>" height="250" width="180"/><br>
          <a href="<%= tip.image %>" target="_blank">크게보기</a> 
        </td>
        <td><%= tip.content %></td>
        <td><%= link_to 'Show', tip %><br>
          <% if tip.user == current_user %>
            <%= link_to 'Edit', edit_tip_path(tip) %><br>
            <%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
        
        <!--댓글작성-->
        <td>
          <form action = "/<%= tip.id%>/comment_tip_create" method= "post">
            댓글 : <textarea name="content"></textarea>
            <button type="submit" class="btn btn-default btn-xs">제출</button>
          </form>
        
        </td>
        
        <!--댓글보기-->
        <td>
          <%tip.comment_tips.each do |c| %>
            <%= fa_icon('comment-alt') %> <%= c.content%>
              <% if c.user == current_user %>
              <%= link_to comment_tip_edit_path(x_id: tip.id, c_id: c.id) do %>
                수정
              <% end %>
              <a href="<%= tip.id %>/comment_tip_destroy/<%= c.id %>"> 삭제 </a>
              <%end%><br>
          <%end%>
        </td>
        <td>
            <% if tip.liked_tip_users.include?(current_user) %>
              <!--좋아요 누름-->
              <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                          like_tip_path(post_id: tip.id), method: :post %>
            <% else %>
              <!--좋아요 안 누름-->
              <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                          like_tip_path(post_id: tip.id), method: :post %>
            <% end %>
            <%= tip.liketips.count %> 명이 좋아합니다. <br><br>
          </td>
        
      </tr>
      
    <% end %>
    
  </tbody>
</table>
<% end%>

app/views/main/_video.html.erb
<% unless current_user.liked_videos.empty? %>
    <table class="table">
      <thead>
        <tr>
          <th>Category</th>
          <th>Title</th>
          <th>Image</th>
          <th>Content</th>
          <th></th>
          <th>댓글 작성</th>
          <th>댓글 보기</th>
          <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
        </tr>
      </thead>
    
      <tbody>
        <% current_user.liked_videos.each do |video| %>
          <tr>
            <td>Video</td>
            <td><%= video.title %></td>
            <td>
              <video width="320" height="240" controls>
                <source src="<%= video.image %>" type="video/mp4">
                <source src="<%= video.image %>" type="video/ogg">
                <source src="<%= video.image %>" type="video/webm">
                <object data="<%= video.image %>" width="320" height="240">
                <embed src="<%= video.image %>" width="320" height="240">
                </object> 
              </video>
            </td>
            <td><%= video.content %></td>
            <td><%= link_to 'Show', video %><br>
              <% if video.user == current_user %>
                <%= link_to 'Edit', edit_video_path(video) %><br>
                <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
            <!--댓글작성-->
            <td>
              <form action = "/<%= video.id%>/comment_video_create" method= "post">
                댓글 : <textarea name="content"></textarea>
                <button type="submit" class="btn btn-default btn-xs">제출</button>
              </form>
            
            </td>
            
            <!--댓글보기-->
            <td>
              <%video.comment_videos.each do |c| %>
                <%= fa_icon('comment-alt') %> <%= c.content%>
                <% if c.user == current_user %>
                  <%= link_to comment_video_edit_path(x_id: video.id, c_id: c.id) do %>
                    수정
                  <% end %>
                  <a href="<%= video.id %>/comment_video_destroy/<%= c.id %>"> 삭제 </a>
                <%end%><br>
              <%end%>
            </td>
            <td>
                <% if video.liked_video_users.include?(current_user) %>
                  <!--좋아요 누름-->
                  <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                              like_video_path(post_id: video.id), method: :post %>
                <% else %>
                  <!--좋아요 안 누름-->
                  <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                              like_video_path(post_id: video.id), method: :post %>
                <% end %>
                <%= video.likevideos.count %> 명이 좋아합니다. <br><br>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/main/mypage.html.erb
<div class="container">
    <hr /> <center><h2><%= current_user.name %>님이 좋아한 글</h2></center>
    
   <%= render 'performance' %>
   <%= render 'post' %>
   <%= render 'tip' %>
   <%= render 'busking' %>
   <%= render 'photo' %>
   <%= render 'video' %>
   
  
  <%#= paginate @tip, theme: 'twitter-bootstrap-4' %>

</div>

<hr />

app/views/main/search.html.erb
<head>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
</head>
<body>
<div class="container">
 
    <center><h1><%= @sdate %>일에는!</h1></center>
    
     <div class="page-header" id="news">
        <h1 class="text-center text-danger">LINE UP</h1>
    </div>
    <table class="table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Title</th>
              <th>Poster</th>
              <th>Seat</th>
              <th>Content</th>
              <th>Show</th>
              <th>Edit</th>
              <th>Destroy</th>
              <th>댓글 작성</th>
              <th>댓글 보기</th>
            </tr>
          </thead>
        
          <tbody>
            <% @performances.each do |performance| %>
            <% if @sdate == performance.day.to_s %>
              <tr>
                <td><%= performance.day %></td>
                <td><%= performance.title %></td>
                <td>
                  <img src="<%= performance.image %>" height="250" width="180"/><br>
                  <a href="<%= performance.image %>" target="_blank">크게보기</a>
                </td>
                <td>
                  <img src="<%= performance.second %>" height="250" width="180"/><br>
                  <a href="<%= performance.second %>" target="_blank">크게보기</a>  
                </td>
                <td><%= performance.content %></td>
                <td><%= link_to 'Show', performance %></td>
                <td><%= link_to 'Edit', edit_performance_path(performance) %></td>
                <td><%= link_to 'Destroy', performance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                
                <!--댓글작성-->
                <td>
                  <form action = "/<%= performance.id%>/comment_per_create" method= "post">
                    댓글 : <textarea name="content"></textarea>
                    <button type="submit" class="btn btn-default btn-xs">제출</button>
                  </form>
                </td>
                
                <!--댓글보기-->
                <td  width="15%">
                  <%performance.comment_pers.each do |c| %>
                    <%= c.content%>
                    <a href="<%= performance.id %>/comment_per_destroy/<%= c.id %>"> 삭제 </a><br>
                  <%end%>
                </td>
              </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
    
    <div class="page-header" id="news">
        <h1 class="text-center text-danger">Busking</h1>
    </div>
    
    <table class="table">
        <thead>
          <tr>
            <th>Day</th>
            <th>Place</th>
            <th>Name</th>
            <th>Image</th>
            <th>Content</th>
            <th colspan="3"></th>
            <th>댓글 작성</th>
            <th>댓글 보기</th>
          </tr>
        </thead>
      
        <tbody>
          <% @buskings.each do |busking| %>
            <% if @sdate == busking.day.to_s %>
            <tr>
              <td><%= busking.day %></td>
              <td><%= busking.place %></td>
              <td><%= busking.name %></td>
              <td>
                <img src="<%= busking.image %>" height="250" width="180"/><br>
                <a href="<%= busking.image %>" target="_blank">크게보기</a> 
              </td>
              <td><%= busking.content %></td>
              <td><%= link_to 'Show', busking %></td>
              <td><%= link_to 'Edit', edit_busking_path(busking) %></td>
              <td><%= link_to 'Destroy', busking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <!--댓글작성-->
              <td>
                <form action = "/<%= busking.id%>/comment_busking_create" method= "post">
                  댓글 : <textarea name="content"></textarea>
                  <button type="submit" class="btn btn-default btn-xs">제출</button>
                </form>
              
              </td>
              
              <!--댓글보기-->
              <td>
                <%busking.comment_buskings.each do |c| %>
                  <%= c.content%>
                  <a href="<%= busking.id %>/comment_busking_destroy/<%= c.id %>"> 삭제 </a><br>
                <%end%>
              </td>
            </tr>
           <% end %>
          <% end %>
          
        </tbody>
      </table>
</div>
</body>