config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :photos
  devise_for :users
  resources :signups
  resources :buskings
  resources :performances
  resources :tips
  resources :posts
  resources :tests
  
  resources :comments, only: [:create, :destroy]
  
  # my page
  get '/my_page', to: 'main#mypage', as: 'my_page'

  root 'main#index'
  get 'users/sign_in'
  get'/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destory'
  
  # 홈화면
  get 'main/index'
  get 'mail/main'
  
  # mail
  get 'mail/index'
  post '/mail/write' => 'mail#write'
  
  # line up
  resources :performances, except: [:show] do
     post "/performance_like", to: "performance_likes#performance_like_toggle"
  end
  post '/:x_id/comment_per_create' => 'performances#comment_create'
  get '/:x_id/comment_per_destroy/:c_id' => 'performances#comment_destroy'
  
  
  get '/performances/performance_like/:performance_id' => 'performances#performance_like'

  
  # community
  resources :posts, except: [:show] do
     post "/like", to: "likes#like_toggle"
  end
  post '/:x_id/comment_create' => 'posts#comment_create'
  get '/:x_id/comment_destroy/:c_id' => 'posts#comment_destroy'
  
  get '/posts/like/:post_id' => 'posts#like'
 
  
  
  post 'performances/result'      => 'performances#result'   # 검색 결과 페이지
  get 'performances/result2/:keyword' => 'performances#result2' #다음카카오 API 결과 페이지
  
  
  post 'tips/result'      => 'tips#result'   # 검색 결과 페이지
  get 'tips/result2/:keyword' => 'tips#result2' #다음카카오 API 결과 페이지
  
  post 'buskings/result'      => 'buskings#result'   # 검색 결과 페이지
  get 'buskings/result2/:keyword' => 'buskings#result2' #다음카카오 API 결과 페이지
  
  post 'posts/result'      => 'posts#result'   # 검색 결과 페이지
  get 'posts/result2/:keyword' => 'posts#result2' #다음카카오 API 결과 페이지
  
  # 날짜로 공연 찾기
  get '/main/search'
  
  # tip
  post '/:x_id/comment_tip_create' => 'tips#comment_create'
  get '/:x_id/comment_tip_destroy/:c_id' => 'tips#comment_destroy'
  
  # busking
  post '/:x_id/comment_busking_create' => 'buskings#comment_create'
  get '/:x_id/comment_busking_destroy/:c_id' => 'buskings#comment_destroy'
  
  # like
  post '/post/:post_id/like_per'      => 'likes#like_per_toggle', as: 'like_per'
  post '/post/:post_id/like'          => 'likes#like_toggle', as: 'like_post'
  post '/post/:post_id/like_tip'      => 'likes#like_tip_toggle', as: 'like_tip'
  post '/post/:post_id/like_busking'  => 'likes#like_busking_toggle', as: 'like_busking'
  post '/post/:post_id/like_photo'    => 'likes#like_photo_toggle', as: 'like_photo'
  post '/post/:post_id/like_video'    => 'likes#like_video_toggle', as: 'like_video'
  
  resources :performances, except: [:show] do
     post "/like", to: "likes#like_toggle"
     end
  
   # video
  post '/:x_id/comment_video_create' => 'videos#comment_create'
  get '/:x_id/comment_video_destroy/:c_id' => 'videos#comment_destroy'
   
   # photo
  post '/:x_id/comment_photo_create' => 'photos#comment_create'
  get '/:x_id/comment_photo_destroy/:c_id' => 'photos#comment_destroy'
  
  # 댓글 수정, 삭제
  get '/:x_id/comment_per_edit/:c_id' => 'performances#comment_per_edit', as: 'comment_per_edit'
  post '/:x_id/comment_per_update/:c_id' => 'performances#comment_per_update', as: 'comment_per_update'
  
  get '/:x_id/comment_comu_edit/:c_id' => 'posts#comment_comu_edit', as: 'comment_comu_edit'
  post '/:x_id/comment_comu_update/:c_id' => 'posts#comment_comu_update', as: 'comment_comu_update'
  
  get '/:x_id/comment_tip_edit/:c_id' => 'tips#comment_tip_edit', as: 'comment_tip_edit'
  post '/:x_id/comment_tip_update/:c_id' => 'tips#comment_tip_update', as: 'comment_tip_update'
  
  get '/:x_id/comment_busking_edit/:c_id' => 'buskings#comment_busking_edit', as: 'comment_busking_edit'
  post '/:x_id/comment_busking_update/:c_id' => 'buskings#comment_busking_update', as: 'comment_busking_update'
  
  get '/:x_id/comment_photo_edit/:c_id' => 'photos#comment_photo_edit', as: 'comment_photo_edit'
  post '/:x_id/comment_photo_update/:c_id' => 'photos#comment_photo_update', as: 'comment_photo_update'
  
  get '/:x_id/comment_video_edit/:c_id' => 'videos#comment_video_edit', as: 'comment_video_edit'
  post '/:x_id/comment_video_update/:c_id' => 'videos#comment_video_update', as: 'comment_video_update'
  
  #ed upon order of creation: first created -> highest priority.
  # See how all your ro
  
  
  # The priority is basutes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/video.rb
class Video < ActiveRecord::Base
    mount_uploader :image, AvatarUploader
    has_many :comment_videos
    belongs_to :user
    has_many :likevideos
    has_many :liked_video_users, through: :likevideos, source: :user
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:home]
  # before_action :check_user, only: [:edit, :destroy]
  
  def comment_video_edit
    @video = Video.find(params[:x_id])
    @comment = Video.find(params[:x_id]).comment_videos.find(params[:c_id])
    
    # if @comment.user != current_user
    #   redirect_to '/videos'
    # end
  end
  
  def comment_video_update
   comment = Video.find(params[:x_id]).comment_videos.find(params[:c_id])
   comment.content = params[:c_content]
   comment.save
    
   redirect_to '/videos'
  end
  
  def comment_create
    comment = Video.find(params[:x_id]).comment_videos.create(content: params[:content])
    comment.user = current_user
    comment.save
    
    redirect_to '/videos'
  end
  
  def comment_destroy
    comment = Video.find(params[:x_id]).comment_videos.find(params[:c_id])
    # if comment.user != current_user
    #   redirect_to '/videos' 
    # else
      comment.destroy
      redirect_to '/videos'
    # end 
  end

  # GET /videos
  # GET /videos.json
  def index
    # @videos = Video.all
    @videos = Video.page(params[:page]).per(5).order(created_at: :desc)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user = current_user
    
    file = params[:image]
    
  uploader = AvatarUploader.new
      
  uploader.store!(file)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :image, :content)
    end
    
    def check_user
      if @video.user != current_user
        redirect_to '/videos' 
      end
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<div class="container">

<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  

<div class="field">
<table  class="table table-condensed">
  <thead>
    <tr>
      <th><%= f.label :title %></th>
      <th> <%= f.label :video %></th>
      <th><%= f.label :content %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.text_field :title %></td>
      <td><%= f.file_field :image, multipart: true, accept: 'image/jpg, image/png, image/gif, image/jpeg' %></td>
      <td> <%= f.text_area :content %></td>
    </tr>
  </tbody>
</table>
</div>

<div class="actions">
    <%= f.submit %>
</div>
  
  
  
<% end %>

app/views/videos/comment_video_edit.html.erb
<center>
<h1><strong>댓글 수정하기</strong></h1><br><br>

<%= form_tag(comment_video_update_path(x_id: @video.id, c_id: @comment.id), method: "post") do %>
    내용:
    <%= text_field_tag 'c_content', @comment.content %><br><br>
    <input type="submit" class="btn" value="수정">
<% end %>
</center>  

app/views/videos/edit.html.erb
<center>
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>
</center>

app/views/videos/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Jua" rel="stylesheet">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1 style="font-family: 'Jua', sans-serif; font-size: 48px"><strong>REVIEW VIDEOS</strong></h1><br>

  <%= link_to 'New Video', new_video_path %>

  <table class="table">
    <thead>
      <tr>
        <th>작성자</th>
        <th>Title</th>
        <th>Image</th>
        <th>Content</th>
        <th></th>
        <th>댓글 작성</th>
        <th>댓글 보기</th>
        <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
      </tr>
    </thead>
  
    <tbody>
      <% @videos.each do |video| %>
        <tr>
          <td><%= video.user.name %></td>
          <td><%= video.title %></td>
          <td>
            <video width="320" height="240" controls>
              <source src="<%= video.image %>" type="video/mp4">
              <source src="<%= video.image %>" type="video/ogg">
              <source src="<%= video.image %>" type="video/webm">
              <object data="<%= video.image %>" width="320" height="240">
              <embed src="<%= video.image %>" width="320" height="240">
              </object> 
            </video>
          </td>
          <td><%= video.content %></td>
          <td><%= link_to 'Show', video %><br>
            <% if video.user == current_user %>
              <%= link_to 'Edit', edit_video_path(video) %><br>
              <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
          <!--댓글작성-->
          <td>
            <form action = "/<%= video.id%>/comment_video_create" method= "post">
              댓글 : <textarea name="content"></textarea>
              <button type="submit" class="btn btn-default btn-xs">제출</button>
            </form>
          
          </td>
          
          <!--댓글보기-->
          <td>
            <%video.comment_videos.each do |c| %>
              <%= fa_icon('comment-alt') %> <%= c.content%>
              <% if c.user == current_user %>
                <%= link_to comment_video_edit_path(x_id: video.id, c_id: c.id) do %>
                  수정
                <% end %>
                <a href="<%= video.id %>/comment_video_destroy/<%= c.id %>"> 삭제 </a>
              <%end%><br>
            <%end%>
          </td>
          <td>
              <% if video.liked_video_users.include?(current_user) %>
                <!--좋아요 누름-->
                <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                            like_video_path(post_id: video.id), method: :post %>
              <% else %>
                <!--좋아요 안 누름-->
                <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                            like_video_path(post_id: video.id), method: :post %>
              <% end %>
              <%= video.likevideos.count %> 명이 좋아합니다. <br><br>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <center><%= paginate @videos, theme: 'twitter-bootstrap-4' %></center>

</div>
<br>

app/views/videos/new.html.erb
<center>
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>
</center>

app/views/videos/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
<div class="container">

<h1><strong>REVIEW VIDEOS</strong></h1><br>


<center>
<p id="notice"><%= notice %></p> 
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th>작성자</th>
      <th>Title</th>
      <th>Image</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @video.user.name %></td>
        <td><%= @video.title %></td>
        <td>
          <video width="320" height="240" controls>
            <source src="<%= @video.image %>" type="video/mp4">
            <source src="<%= @video.image %>" type="video/ogg">
            <source src="<%= @video.image %>" type="video/webm">
            <object data="<%= @video.image %>" width="320" height="240">
            <embed src="<%= @video.image %>" width="320" height="240">
            </object> 
          </video>
        </td>
        <td><%= @video.content %></td>
       </tr>
    
  </tbody>
</table>


<%= link_to 'Edit', edit_busking_path(@video) %> |
<%= link_to 'Back', videos_path %>
</div>
</center>