config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :photos
  devise_for :users
  resources :signups
  resources :buskings
  resources :performances
  resources :tips
  resources :posts
  resources :tests
  
  resources :comments, only: [:create, :destroy]
  
  # my page
  get '/my_page', to: 'main#mypage', as: 'my_page'

  root 'main#index'
  get 'users/sign_in'
  get'/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destory'
  
  # 홈화면
  get 'main/index'
  get 'mail/main'
  
  # mail
  get 'mail/index'
  post '/mail/write' => 'mail#write'
  
  # line up
  resources :performances, except: [:show] do
     post "/performance_like", to: "performance_likes#performance_like_toggle"
  end
  post '/:x_id/comment_per_create' => 'performances#comment_create'
  get '/:x_id/comment_per_destroy/:c_id' => 'performances#comment_destroy'
  
  
  get '/performances/performance_like/:performance_id' => 'performances#performance_like'

  
  # community
  resources :posts, except: [:show] do
     post "/like", to: "likes#like_toggle"
  end
  post '/:x_id/comment_create' => 'posts#comment_create'
  get '/:x_id/comment_destroy/:c_id' => 'posts#comment_destroy'
  
  get '/posts/like/:post_id' => 'posts#like'
 
  
  
  post 'performances/result'      => 'performances#result'   # 검색 결과 페이지
  get 'performances/result2/:keyword' => 'performances#result2' #다음카카오 API 결과 페이지
  
  
  post 'tips/result'      => 'tips#result'   # 검색 결과 페이지
  get 'tips/result2/:keyword' => 'tips#result2' #다음카카오 API 결과 페이지
  
  post 'buskings/result'      => 'buskings#result'   # 검색 결과 페이지
  get 'buskings/result2/:keyword' => 'buskings#result2' #다음카카오 API 결과 페이지
  
  post 'posts/result'      => 'posts#result'   # 검색 결과 페이지
  get 'posts/result2/:keyword' => 'posts#result2' #다음카카오 API 결과 페이지
  
  # 날짜로 공연 찾기
  get '/main/search'
  
  # tip
  post '/:x_id/comment_tip_create' => 'tips#comment_create'
  get '/:x_id/comment_tip_destroy/:c_id' => 'tips#comment_destroy'
  
  # busking
  post '/:x_id/comment_busking_create' => 'buskings#comment_create'
  get '/:x_id/comment_busking_destroy/:c_id' => 'buskings#comment_destroy'
  
  # like
  post '/post/:post_id/like_per'      => 'likes#like_per_toggle', as: 'like_per'
  post '/post/:post_id/like'          => 'likes#like_toggle', as: 'like_post'
  post '/post/:post_id/like_tip'      => 'likes#like_tip_toggle', as: 'like_tip'
  post '/post/:post_id/like_busking'  => 'likes#like_busking_toggle', as: 'like_busking'
  post '/post/:post_id/like_photo'    => 'likes#like_photo_toggle', as: 'like_photo'
  post '/post/:post_id/like_video'    => 'likes#like_video_toggle', as: 'like_video'
  
  resources :performances, except: [:show] do
     post "/like", to: "likes#like_toggle"
     end
  
   # video
  post '/:x_id/comment_video_create' => 'videos#comment_create'
  get '/:x_id/comment_video_destroy/:c_id' => 'videos#comment_destroy'
   
   # photo
  post '/:x_id/comment_photo_create' => 'photos#comment_create'
  get '/:x_id/comment_photo_destroy/:c_id' => 'photos#comment_destroy'
  
  # 댓글 수정, 삭제
  get '/:x_id/comment_per_edit/:c_id' => 'performances#comment_per_edit', as: 'comment_per_edit'
  post '/:x_id/comment_per_update/:c_id' => 'performances#comment_per_update', as: 'comment_per_update'
  
  get '/:x_id/comment_comu_edit/:c_id' => 'posts#comment_comu_edit', as: 'comment_comu_edit'
  post '/:x_id/comment_comu_update/:c_id' => 'posts#comment_comu_update', as: 'comment_comu_update'
  
  get '/:x_id/comment_tip_edit/:c_id' => 'tips#comment_tip_edit', as: 'comment_tip_edit'
  post '/:x_id/comment_tip_update/:c_id' => 'tips#comment_tip_update', as: 'comment_tip_update'
  
  get '/:x_id/comment_busking_edit/:c_id' => 'buskings#comment_busking_edit', as: 'comment_busking_edit'
  post '/:x_id/comment_busking_update/:c_id' => 'buskings#comment_busking_update', as: 'comment_busking_update'
  
  get '/:x_id/comment_photo_edit/:c_id' => 'photos#comment_photo_edit', as: 'comment_photo_edit'
  post '/:x_id/comment_photo_update/:c_id' => 'photos#comment_photo_update', as: 'comment_photo_update'
  
  get '/:x_id/comment_video_edit/:c_id' => 'videos#comment_video_edit', as: 'comment_video_edit'
  post '/:x_id/comment_video_update/:c_id' => 'videos#comment_video_update', as: 'comment_video_update'
  
  #ed upon order of creation: first created -> highest priority.
  # See how all your ro
  
  
  # The priority is basutes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comment_comus
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    acts_as_commentable
    
    def self.search(search)
        where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:home]
  # before_action :check_user, only: [:edit, :destroy]
  
  def comment_comu_edit
    @post = Post.find(params[:x_id])
    @comment = Post.find(params[:x_id]).comment_comus.find(params[:c_id])
    
    # if @comment.user != current_user
    #   redirect_to '/posts'
    # end
  end
  
  def comment_comu_update
   comment = Post.find(params[:x_id]).comment_comus.find(params[:c_id])
   comment.content = params[:c_content]
   comment.save
    
   redirect_to '/posts'
  end
  
  def comment_create
    comment = Post.find(params[:x_id]).comment_comus.create(content: params[:content])
    comment.user = current_user
    comment.save
    
    redirect_to '/posts'
  end
  
  def comment_destroy
    comment = Post.find(params[:x_id]).comment_comus.find(params[:c_id])
    # if comment.user != current_user
    #   redirect_to '/posts' 
    # else
      comment.destroy
      redirect_to '/posts'
    # end 
    
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post         = Post.find(params[:id])
    @new_comment  = Comment.build_from(@post, current_user.id, "")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    # check_user
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    # check_user
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
 
  end
  
  # 검색 결과
  def result
    if params[:search]
      @resultPost = Post.search(params[:search]).reverse
      @keyword = params[:search]
    end
  end  
  
  def result2
    # 키워드검색
    @keyword = params[:keyword]
    url = "https://dapi.kakao.com/v2/search/vclip?query=" + @keyword
    uri = URI.encode(url)
    res = RestClient.get(uri, headers={'Authorization':'KakaoAK 63c5d677e72eed7c4670c433997d1975'})
    
    unitokor = eval(res)   
    json_g =  JSON.generate(unitokor)
    hash = JSON.parse(json_g)
        
    @item = hash['documents']
    
    # 동영상검색
    url_ = "https://dapi.kakao.com/v2/search/web?query=" + @keyword
    uri_ = URI.encode(url_)
    res_ = RestClient.get(uri_, headers={'Authorization':'KakaoAK 63c5d677e72eed7c4670c433997d1975'})
    
    unitokor_ = eval(res_)   
    json_g_ =  JSON.generate(unitokor_)
    hash_ = JSON.parse(json_g_)
        
    @item_ = hash_['documents']
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
    
    def check_user
      if @post.user != current_user
        redirect_to '/posts' 
      end
    end
 
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<div class="container">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<table  class="table table-condensed">
  <thead>
    <tr>
      <th><%= f.label :title %></th>
      <th><%= f.label :content %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.text_field :title %></td>
      <td> <%= f.text_area :content %></td>
    </tr>
  </tbody>
</table>
</div>

<div class="actions">
    <%= f.submit %>
</div>

<% end %>
</div>

app/views/posts/comment_comu_edit.html.erb
<center>
<h1><strong>댓글 수정하기</strong></h1><br><br>

<%= form_tag(comment_comu_update_path(x_id: @post.id, c_id: @comment.id), method: "post") do %>
    내용:
    <%= text_field_tag 'c_content', @comment.content %><br><br>
    <input type="submit"  class="btn" value="수정">
<% end %>

</center>  

app/views/posts/edit.html.erb
<center>
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</center>

app/views/posts/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Jua" rel="stylesheet">

<div class="container">

<h1 style="font-family: 'Jua', sans-serif; font-size: 48px"><i class="fa fa-comment-o" style="font-size:48px"></i><strong>COMMUNITY</strong></h1><br>
<%= link_to 'New Post', new_post_path %><br><br>
<center>
<p id="notice"><%= notice %></p>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<!--게시글 검색/다음 카카오 검색API-->
<%= form_tag('posts/result') do %>
    <div class="form-group row">
        <div class="col-md-4 col-md-offset-3">
            <input type="text" name="search" class="form-control text-center" placeholder="검색어">
        </div>
        <div class="col-md-2">
              <button type="submit" class="btn btn-success form-control">검색하기</button>
        </div>
    </div>
<% end %>

<table class="table">
  <thead>
    <tr >
      <th>작성자</th>
      <th >title</th>
      <th >content</th>
      <th></th>
      <th>댓글 작성</th>
      <th>댓글 보기</th>
      <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %><br>
          <% if post.user == current_user %>
            <%= link_to 'Edit', edit_post_path(post) %><br>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
        <!--댓글작성-->
        <td>
          <form action = "/<%=post.id%>/comment_create" method= "post">
            댓글 : <textarea name="content"></textarea>
            <button type="submit" class="btn btn-default btn-xs">제출</button>
          </form>
        </td>
        
        <!--댓글보기-->
        
        <td>
          <% post.comment_comus.each do |c| %>
            <%= fa_icon('comment-alt') %> <%= c.content%>
            <% if c.user == current_user %>
              <%= link_to comment_comu_edit_path(x_id: post.id, c_id: c.id) do %>
                수정
              <% end %>
              <a href="<%= post.id %>/comment_destroy/<%= c.id %>"> 삭제 </a>
            <%end%><br>
          <%end%>
        </td>
        <td> 
          <% if post.liked_users.include?(current_user) %>
            <!--좋아요 누름-->
            <%= link_to fa_icon('heart', style: 'font-size:24px; color: red;'), 
                        like_post_path(post_id: post.id), method: :post %>
          <% else %>
            <!--좋아요 안 누름-->
            <%= link_to fa_icon('heart', style: "font-size:24px; color: grey;"), 
                        like_post_path(post_id: post.id), method: :post %>
          <% end %>
          <%= post.likes.count %> 명이 좋아합니다. <br><br>
        </td>
      </tr>
      
      
    <% end %>
  </tbody>
</table>

<br>

</center>
<center><%= paginate @posts, theme: 'twitter-bootstrap-4' %></center>
</div>

app/views/posts/new.html.erb
<center>
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</center>

app/views/posts/result.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>


<body>

<div class="container">
<p id="notice"><%= notice %></p>

<!--<h3>-->
<!--  <a href='/'><i class="fas fa-home"></i>Main</a> -->
<!--  |-->
<!--  <a href='/posts'>Community</a>-->
<!--  |-->
<!--  <a href='/tips'>Tips</a>-->
<!--  |-->
<!--  <a href= '/buskings'>Buskings</a>-->
<!--  |-->
<!--  <a href='/photos'>Review Photos</a>-->
<!--  |-->
<!--  <a href='/videos'>Review Video</a>-->
<!--  |-->
<!--  <a href='/mail/main'>Mail</a>-->
<!--</h3>-->

</br></br></br>

<h1>SEARCH RESULT</h1>
  
<hr>

<% if @resultPost.empty? %>
    <h3><b class="text-warning"><%= @keyword %></b>에 대한 검색 결과가 없습니다.</a></h3>
    <!-- 검색 결과 없으면 카카오(다음) 검색 API 사용, 카카오 검색 결과 보여주기 -->
    <%= link_to @keyword + '에 대한 다음(kakao) 검색 결과 확인하기', "./result2/"+@keyword  %>
<% else %>

 <h4><b class="text-warning"><%= @keyword %></b>에 대한 검색결과입니다.</a></h4>
    <table class="table table-hover table-striped">
        <thead>
            <th width="100px">글 번호</th>
            <th>글 제목</th>
            <th width="60px"></th>
        </thead>
        <tbody>
            <% @resultPost.each do |onePost| %>
                <tr>
                    <td><%= onePost.id %></td>
                    <td>
                        <%= link_to onePost.title, "show/#{onePost.id}" %>
                    </td>
                    <td>
                        <%= link_to '', "/edit/#{onePost.id}", class: "glyphicon glyphicon-pencil" %>&nbsp;
                        <%= link_to '', "/destroy/#{onePost.id}", class: "glyphicon glyphicon-remove" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        <tfoot>
            
        </tfoot>
    </table>
<% end %>

<div class="form-group row">
    <div class="col-md-2 col-md-offset-10">
        <a href="/posts" class="btn btn-default">목록으로 돌아가기</a>
    </div>
</div>

app/views/posts/result2.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>


<body>

<div class="container">
<p id="notice"><%= notice %></p>

<h3>
  <a href='/'><i class="fas fa-home"></i>Main</a> 
  |
  <a href='/posts'>Community</a>
  |
  <a href='/tips'>Tips</a>
  |
  <a href= '/buskings'>Buskings</a>
  |
  <a href='/photos'>Review Photos</a>
  |
  <a href='/videos'>Review Video</a>
  |
  <a href='/mail/main'>Mail</a>
</h3>

</br></br></br>

<div class="form-group row">
    <div class="col-md-2 col-md-offset-10">
        <a href="/posts" class="btn btn-default">목록으로 돌아가기</a>
    </div>
</div></br>

<h4><b class="text-warning"><%= @keyword %></b>에 대한 카카오(다음) 키워드검색결과입니다.</a></h4>
<table class="table table-hover table-striped">
  <thead>
    <th width="400px">글 제목</th>
    <th>글 내용</th>
  </thead>
  <tbody>
    <% @item_.each do |iteminfo| %>
      <tr>
        <td>
          <%= link_to iteminfo['title'].html_safe,  iteminfo['url'] %>
        </td>
        <td>
          <%= iteminfo['contents'].html_safe %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br><br>
  
<h4><b class="text-warning"><%= @keyword %></b>에 대한 카카오(다음) 영상검색결과입니다.</a></h4></br>
<div class="container">
  <% @item.each do |iteminfo| %>
  <div class="col-sm-4">
  <div class= class="card bg-light" style="width:350px; height=500px;">
    <a href = "<%= iteminfo['url'].html_safe %>"><img class="card-img-top" src="<%= iteminfo['thumbnail'].html_safe %>" style="width:100%; height=300px;"></a>
    <div class="card-body">
      <center><p class="card-title">제목: <%= iteminfo['title'].html_safe %></p></center>
    </div>
  </div>
  </div>
  <% end %>
</div>

</body>

app/views/posts/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
<div class="container">

<h1><strong>COMMUNNITY</strong></h1><br>


<center>
<p id="notice"><%= notice %></p>

<table class="table">
    <thead>
      <tr>
        <th>작성자</th>
        <th>Title</th>
        <th>Content</th>
        <th><i class="fa fa-heart" style="font-size:24px;color:red"></i></th>
    </thead>
    
    <tbody>
      <tr>
        <td><%= @post.user.name %></td>
        <td><%= @post.title %></td>
        <td><%= @post.content %></td>
        <td><strong>Like:</strong>
        <%= @post.likes.size %> 명이 좋아합니다. </td>
      </tr>
     
    </tbody>
</table><br>
 
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</center>
</div>
</body>